import type { runStandardAnswerFlow, tryHandlePvpAnswer } from './answerFlow.ts';
import type { tryProcessPvpTextAdvance } from './advanceFlow.ts';
import type { runEnemyTurn } from './enemyFlow.ts';

type EnemyTurnHandlers = Parameters<typeof runEnemyTurn>[0];
type PvpAnswerHandlers = Parameters<typeof tryHandlePvpAnswer>[0]['handlers'];
type PlayerAnswerHandlers = Parameters<typeof runStandardAnswerFlow>[0]['handlers'];
type PvpTurnStartHandlers = Parameters<typeof tryProcessPvpTextAdvance>[0]['handlers'];

export function createEnemyTurnHandlers(deps: EnemyTurnHandlers): EnemyTurnHandlers {
  return {
    sr: deps.sr,
    safeTo: deps.safeTo,
    rand: deps.rand,
    randInt: deps.randInt,
    chance: deps.chance,
    sfx: deps.sfx,
    setSealedTurns: deps.setSealedTurns,
    setSealedMove: deps.setSealedMove,
    setBossPhase: deps.setBossPhase,
    setBossTurn: deps.setBossTurn,
    setBossCharging: deps.setBossCharging,
    setBText: deps.setBText,
    setPhase: deps.setPhase,
    setEAnim: deps.setEAnim,
    setPAnim: deps.setPAnim,
    setPHp: deps.setPHp,
    setPHpSub: deps.setPHpSub,
    setSpecDef: deps.setSpecDef,
    setDefAnim: deps.setDefAnim,
    setEHp: deps.setEHp,
    setEffMsg: deps.setEffMsg,
    setCursed: deps.setCursed,
    addD: deps.addD,
    addP: deps.addP,
    _endSession: deps._endSession,
    setScreen: deps.setScreen,
    handleVictory: deps.handleVictory,
    handlePlayerPartyKo: deps.handlePlayerPartyKo,
    t: deps.t,
  };
}

export function createPvpAnswerHandlers(deps: PvpAnswerHandlers): PvpAnswerHandlers {
  return {
    sr: deps.sr,
    rand: deps.rand,
    chance: deps.chance,
    safeTo: deps.safeTo,
    sfx: deps.sfx,
    getOtherPvpTurn: deps.getOtherPvpTurn,
    setFb: deps.setFb,
    setTC: deps.setTC,
    setTW: deps.setTW,
    setPvpChargeP1: deps.setPvpChargeP1,
    setPvpChargeP2: deps.setPvpChargeP2,
    setPvpComboP1: deps.setPvpComboP1,
    setPvpComboP2: deps.setPvpComboP2,
    setPvpTurn: deps.setPvpTurn,
    setPvpActionCount: deps.setPvpActionCount,
    setBText: deps.setBText,
    setPhase: deps.setPhase,
    setPvpSpecDefP1: deps.setPvpSpecDefP1,
    setPvpSpecDefP2: deps.setPvpSpecDefP2,
    setEffMsg: deps.setEffMsg,
    setAtkEffect: deps.setAtkEffect,
    addP: deps.addP,
    setPvpParalyzeP1: deps.setPvpParalyzeP1,
    setPvpParalyzeP2: deps.setPvpParalyzeP2,
    setPAnim: deps.setPAnim,
    setEAnim: deps.setEAnim,
    addD: deps.addD,
    setPHp: deps.setPHp,
    setPvpHp2: deps.setPvpHp2,
    setEHp: deps.setEHp,
    setScreen: deps.setScreen,
    setPvpWinner: deps.setPvpWinner,
    setPvpBurnP1: deps.setPvpBurnP1,
    setPvpBurnP2: deps.setPvpBurnP2,
    setPvpFreezeP1: deps.setPvpFreezeP1,
    setPvpFreezeP2: deps.setPvpFreezeP2,
    setPvpStaticP1: deps.setPvpStaticP1,
    setPvpStaticP2: deps.setPvpStaticP2,
    t: deps.t,
  };
}

export function createPlayerAnswerHandlers(deps: PlayerAnswerHandlers): PlayerAnswerHandlers {
  return {
    sr: deps.sr,
    safeTo: deps.safeTo,
    chance: deps.chance,
    sfx: deps.sfx,
    getCollectionDamageScale: deps.getCollectionDamageScale,
    setFb: deps.setFb,
    setTC: deps.setTC,
    setTW: deps.setTW,
    setStreak: deps.setStreak,
    setPassiveCount: deps.setPassiveCount,
    setCharge: deps.setCharge,
    setMaxStreak: deps.setMaxStreak,
    setSpecDef: deps.setSpecDef,
    tryUnlock: deps.tryUnlock,
    setMLvls: deps.setMLvls,
    setMLvlUp: deps.setMLvlUp,
    setMHits: deps.setMHits,
    setPhase: deps.setPhase,
    setPAnim: deps.setPAnim,
    setAtkEffect: deps.setAtkEffect,
    setEAnim: deps.setEAnim,
    setEffMsg: deps.setEffMsg,
    setBossCharging: deps.setBossCharging,
    setBurnStack: deps.setBurnStack,
    setPHp: deps.setPHp,
    setPHpSub: deps.setPHpSub,
    setFrozen: deps.setFrozen,
    frozenR: deps.frozenR,
    setStaticStack: deps.setStaticStack,
    setEHp: deps.setEHp,
    addD: deps.addD,
    doEnemyTurn: deps.doEnemyTurn,
    handleVictory: deps.handleVictory,
    handleFreeze: deps.handleFreeze,
    setCursed: deps.setCursed,
    setShadowShieldCD: deps.setShadowShieldCD,
    setFuryRegenUsed: deps.setFuryRegenUsed,
    _endSession: deps._endSession,
    setScreen: deps.setScreen,
    setBText: deps.setBText,
    handlePlayerPartyKo: deps.handlePlayerPartyKo,
    runAllySupportTurn: deps.runAllySupportTurn,
    t: deps.t,
  };
}

export function createPvpTurnStartHandlers(deps: PvpTurnStartHandlers): PvpTurnStartHandlers {
  return {
    sr: deps.sr,
    safeTo: deps.safeTo,
    getOtherPvpTurn: deps.getOtherPvpTurn,
    getPvpTurnName: deps.getPvpTurnName,
    setPHp: deps.setPHp,
    setPvpBurnP1: deps.setPvpBurnP1,
    setPAnim: deps.setPAnim,
    addD: deps.addD,
    setPvpWinner: deps.setPvpWinner,
    setScreen: deps.setScreen,
    setPvpHp2: deps.setPvpHp2,
    setEHp: deps.setEHp,
    setPvpBurnP2: deps.setPvpBurnP2,
    setEAnim: deps.setEAnim,
    setBText: deps.setBText,
    setPhase: deps.setPhase,
    setPvpParalyzeP1: deps.setPvpParalyzeP1,
    setPvpParalyzeP2: deps.setPvpParalyzeP2,
    setPvpTurn: deps.setPvpTurn,
    setPvpFreezeP1: deps.setPvpFreezeP1,
    setPvpFreezeP2: deps.setPvpFreezeP2,
    t: deps.t,
  };
}
